public enum MsgType {
    /* 서버가 클라이언트로 보내는 메시지 */
    LOGIN_SUCCESS, LOGIN_FAILED,
    SIGNUP_SUCCESS, SIGNUP_FAILED,
    MAKE_SUCCESS, MAKE_FAILED,
    JOIN_SUCCESS, JOIN_FAILED,
    EXIT_SUCCESS, EXIT_FAILED,
    FILE_LIST,

    /* 클라이언트가 서버로 보내는 메시지 */
    LOGIN, SIGNUP,
    INFO, MAKE, FILE_INFO, DOWNLOAD,

    /* 공통 메시지 */
    JOIN, EXIT, SEND,
    UPLOAD_START, UPLOAD_DOING, UPLOAD_END,
    DOWNLOAD_READY, DOWNLOAD_DOING, DOWNLOAD_END
}